=== sad-sadie/DC_Labs/Lab7-part1/src/main/resources/university.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.nure.ua"
           xmlns="http://www.nure.ua"
           elementFormDefault="qualified">

    <xs:element name = "university">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="group" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="student" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                        <xs:attribute type="xs:integer" name="id"/>
                                        <xs:attribute type="xs:string" name="firstName"/>
                                        <xs:attribute type="xs:string" name="lastName"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:integer" name="id"/>
                        <xs:attribute type="xs:string" name="name"/>
                        <xs:attribute type="xs:integer" name="course"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== sad-sadie/DC_Labs/Lab7-part1/src/main/resources/university.xml
<university xmlns="http://www.nure.ua"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.nure.ua university.xsd ">
    <group course="1" id="1" name="group-1">
        <student id="1" firstName="Vova" lastName="Kirilov"/>
        <student id="2" firstName="Illia" lastName="Kuzkuz"/>
        <student id="4" firstName="Kyryl" lastName="Shcupshchup"/>
        <student id="5" firstName="Kyryl" lastName="Shcupshchup"/>
    </group>
    <group course="2" id="2" name="group-2">
        <student id="3" firstName="student" lastName="stud"/>
    </group>
</university>
